apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant
spec:
  selector:
    matchLabels:
      app: qdrant
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
