# -----------------------------------------------------------
# SERVICE ACCOUNT RESOURCE
# Defines an identity used by Pods when communicating
# with the Kubernetes API server.
#
# ServiceAccounts are commonly used with RBAC permissions
# to control access inside the cluster.
# -----------------------------------------------------------
apiVersion: v1


# -----------------------------------------------------------
# RESOURCE TYPE
# Declares this object as a ServiceAccount resource.
# -----------------------------------------------------------
kind: ServiceAccount


# -----------------------------------------------------------
# METADATA
# Provides identification details for the ServiceAccount.
# -----------------------------------------------------------
metadata:

  # Name referenced in Deployment spec
  name: {{ .Values.serviceAccount.name }}